# Generated by Django 5.1 on 2024-09-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='nutrition_goals',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
