# Generated by Django 5.0.8 on 2024-10-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_cita_disponibilidaddoctor_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='contacto_emergencia',
            new_name='numero_emergencia',
        ),
    ]
