# Generated by Django 5.0.8 on 2024-10-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_ingredientanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='weight',
            new_name='peso',
        ),
    ]
